In [3]:
import pandas as pd

file_path = "/content/Dataset for Data Analytics.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Sheets available:")
print(excel_file.sheet_names)

Sheets available:
['Sheet1']

In [4]:
print("HELLO")

HELLO

In [5]:
import os

print(os.listdir("/content"))

['.config', 'Dataset for Data Analytics.xlsx', 'sample_data']

In [6]:
import pandas as pd

file_path = "/content/Dataset for Data Analytics.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Sheets available:")
print(excel_file.sheet_names)

Sheets available:
['Sheet1']

In [7]:
df = pd.read_excel("/content/Dataset for Data Analytics.xlsx", sheet_name="Sheet1")

print("Rows and columns:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Rows and columns: (1200, 14)

Column names:
['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

First 5 rows:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [8]:
print("Dataset shape:", df.shape)

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (1200, 14)

Data types:
OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

Missing values:
OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

Duplicate rows: 0

In [9]:
import sqlite3

# Create an in-memory SQL database
conn = sqlite3.connect(":memory:")

# Load Excel data into SQL table
df.to_sql("orders", conn, index=False, if_exists="replace")

print("SQL table 'orders' created successfully!")

SQL table 'orders' created successfully!

In [10]:
query = """
SELECT *
FROM orders
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23 00:00:00,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17 00:00:00,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12 00:00:00,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02 00:00:00,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,None,Email,268.56
9,ORD200009,2023-11-21 00:00:00,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

In [11]:
query = """
SELECT
    COUNT(*) AS Total_Orders,
    SUM(Quantity) AS Total_Quantity_Sold,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Total_Orders  Total_Quantity_Sold  Total_Sales
0          1200                 3535   1264761.96

In [12]:
query = """
SELECT
    Product,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY Product
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Product  Number_of_Orders  Total_Quantity  Total_Sales
0    Chair               178             562    195620.11
1  Printer               181             542    195612.61
2   Laptop               173             535    192126.56
3   Tablet               179             497    186568.95
4  Monitor               163             480    175651.41
5     Desk               170             508    167459.93
6    Phone               156             411    151722.39

In [13]:
query = """
SELECT
    OrderStatus,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY OrderStatus
ORDER BY Number_of_Orders DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

  OrderStatus  Number_of_Orders  Total_Quantity  Total_Sales
0   Cancelled               250             759    276396.21
1    Returned               247             682    243277.70
2     Pending               237             724    256328.15
3     Shipped               235             680    246159.58
4   Delivered               231             690    242600.32

In [14]:
query = """
SELECT
    PaymentMethod,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY PaymentMethod
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

  PaymentMethod  Number_of_Orders  Total_Quantity  Total_Sales
0   Credit Card               234             712    263847.63
1        Online               258             731    262442.94
2          Cash               246             753    259786.29
3     Gift Card               230             675    246323.92
4    Debit Card               232             664    232361.18

In [15]:
query = """
SELECT
    ReferralSource,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY ReferralSource
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

  ReferralSource  Number_of_Orders  Total_Quantity  Total_Sales
0      Instagram               259             770    275285.45
1          Email               250             746    261808.55
2         Google               241             714    250441.48
3       Facebook               228             674    250410.90
4       Referral               222             631    226815.58

In [16]:
query = """
SELECT
    COALESCE(CouponCode, 'No Coupon') AS Coupon_Code,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY CouponCode
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

  Coupon_Code  Number_of_Orders  Total_Quantity  Total_Sales
0    FREESHIP               313             914    335036.99
1   No Coupon               309             941    322401.41
2      SAVE10               286             844    304840.02
3    WINTER15               292             836    302483.54

In [17]:
query = """
SELECT
    strftime('%Y', Date) AS Year,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY strftime('%Y', Date)
ORDER BY Year;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Year  Number_of_Orders  Total_Quantity  Total_Sales
0  2023               510            1524    552643.24
1  2024               459            1351    480235.87
2  2025               231             660    231882.85

In [18]:
query = """
SELECT
    strftime('%Y-%m', Date) AS Month,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY strftime('%Y-%m', Date)
ORDER BY Month;
"""

result = pd.read_sql_query(query, conn)
display(result)

      Month  Number_of_Orders  Total_Quantity  Total_Sales
0   2023-01                47             146     56685.75
1   2023-02                37             102     40117.66
2   2023-03                43             126     48609.37
3   2023-04                31              84     27751.71
4   2023-05                49             148     63836.84
5   2023-06                45             146     49500.19
6   2023-07                44             119     42820.66
7   2023-08                51             174     54352.14
8   2023-09                29              86     29526.67
9   2023-10                47             150     52607.85
10  2023-11                41             114     43079.67
11  2023-12                46             129     43754.73
12  2024-01                32             102     38528.08
13  2024-02                32             102     36909.57
14  2024-03                36             108     36030.90
15  2024-04                50             147     49613.14
16  2024-05                34              95     27909.11
17  2024-06                53             166     68068.54
18  2024-07                43             124     42963.98
19  2024-08                28              86     31991.07
20  2024-09                44             122     39794.98
21  2024-10                31              91     37226.97
22  2024-11                35              97     32413.76
23  2024-12                41             111     38785.77
24  2025-01                27              80     29099.40
25  2025-02                37              99     35317.55
26  2025-03                49             133     39200.66
27  2025-04                32              89     31821.20
28  2025-05                37             113     43396.64
29  2025-06                49             146     53047.40

In [19]:
query = """
SELECT
    COUNT(*) AS Total_Orders,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value,
    ROUND(AVG(Quantity), 2) AS Average_Quantity_Per_Order
FROM orders;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Total_Orders  Total_Sales  Average_Order_Value  Average_Quantity_Per_Order
0          1200   1264761.96              1053.97                        2.95

In [20]:
query = """
SELECT
    CustomerID,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY CustomerID
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

  CustomerID  Number_of_Orders  Total_Quantity  Total_Sales
0     C38840                 2               9      5723.23
1     C57276                 1               5      3456.40
2     C67260                 1               5      3390.80
3     C13877                 1               5      3384.90
4     C18404                 1               5      3370.20
5     C16775                 1               5      3353.75
6     C65986                 1               5      3352.40
7     C47778                 1               5      3334.00
8     C59183                 1               5      3322.55
9     C25276                 1               5      3313.90

In [21]:
query = """
SELECT
    ShippingAddress,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY ShippingAddress
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

  ShippingAddress  Number_of_Orders  Total_Quantity  Total_Sales
0     533 Main St                 8              19      7753.73
1     558 Main St                 4              13      7527.40
2     740 Main St                 5              15      6761.84
3     747 Main St                 5              19      6700.24
4     811 Main St                 3              12      6668.36
5     160 Main St                 4              14      6536.79
6     552 Main St                 4              13      6521.03
7     619 Main St                 3              14      6380.38
8     922 Main St                 3              11      6367.75
9     165 Main St                 2              10      6161.45

In [22]:
query = """
SELECT
    Product,
    ROUND(AVG(UnitPrice), 2) AS Average_Unit_Price,
    ROUND(MIN(UnitPrice), 2) AS Minimum_Unit_Price,
    ROUND(MAX(UnitPrice), 2) AS Maximum_Unit_Price
FROM orders
GROUP BY Product
ORDER BY Average_Unit_Price DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Product  Average_Unit_Price  Minimum_Unit_Price  Maximum_Unit_Price
0    Phone              375.22               11.39              695.10
1   Tablet              367.68               17.24              699.88
2  Monitor              358.66               14.69              696.71
3   Laptop              357.71               18.20              699.93
4    Chair              355.66               14.93              695.29
5  Printer              351.71               12.10              697.19
6     Desk              329.61               26.95              697.93

In [23]:
query = """
SELECT
    OrderStatus,
    COUNT(*) AS Number_of_Orders,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
FROM orders
GROUP BY OrderStatus
ORDER BY Average_Order_Value DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

  OrderStatus  Number_of_Orders  Total_Sales  Average_Order_Value
0   Cancelled               250    276396.21              1105.58
1     Pending               237    256328.15              1081.55
2   Delivered               231    242600.32              1050.22
3     Shipped               235    246159.58              1047.49
4    Returned               247    243277.70               984.93

In [24]:
query = """
SELECT
    strftime('%Y-%m', Date) AS Month,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY strftime('%Y-%m', Date)
ORDER BY Month;
"""

result = pd.read_sql_query(query, conn)
display(result)

      Month  Number_of_Orders  Total_Quantity  Total_Sales
0   2023-01                47             146     56685.75
1   2023-02                37             102     40117.66
2   2023-03                43             126     48609.37
3   2023-04                31              84     27751.71
4   2023-05                49             148     63836.84
5   2023-06                45             146     49500.19
6   2023-07                44             119     42820.66
7   2023-08                51             174     54352.14
8   2023-09                29              86     29526.67
9   2023-10                47             150     52607.85
10  2023-11                41             114     43079.67
11  2023-12                46             129     43754.73
12  2024-01                32             102     38528.08
13  2024-02                32             102     36909.57
14  2024-03                36             108     36030.90
15  2024-04                50             147     49613.14
16  2024-05                34              95     27909.11
17  2024-06                53             166     68068.54
18  2024-07                43             124     42963.98
19  2024-08                28              86     31991.07
20  2024-09                44             122     39794.98
21  2024-10                31              91     37226.97
22  2024-11                35              97     32413.76
23  2024-12                41             111     38785.77
24  2025-01                27              80     29099.40
25  2025-02                37              99     35317.55
26  2025-03                49             133     39200.66
27  2025-04                32              89     31821.20
28  2025-05                37             113     43396.64
29  2025-06                49             146     53047.40

In [25]:
query = """
SELECT
    OrderID,
    Date,
    CustomerID,
    Product,
    Quantity,
    ROUND(UnitPrice, 2) AS UnitPrice,
    ROUND(TotalPrice, 2) AS TotalPrice,
    OrderStatus,
    PaymentMethod
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,TotalPrice,OrderStatus,PaymentMethod
0,ORD200789,2023-08-17 00:00:00,C57276,Tablet,5,691.28,3456.40,Delivered,Online
1,ORD201122,2023-06-07 00:00:00,C38840,Monitor,5,678.19,3390.95,Returned,Online
2,ORD200632,2023-05-02 00:00:00,C67260,Laptop,5,678.16,3390.80,Delivered,Gift Card
3,ORD200469,2023-11-26 00:00:00,C13877,Chair,5,676.98,3384.90,Cancelled,Cash
4,ORD200328,2023-02-28 00:00:00,C18404,Tablet,5,674.04,3370.20,Cancelled,Online
5,ORD200107,2023-03-27 00:00:00,C16775,Printer,5,670.75,3353.75,Shipped,Gift Card
6,ORD200326,2024-07-01 00:00:00,C65986,Laptop,5,670.48,3352.40,Returned,Gift Card
7,ORD201065,2023-10-30 00:00:00,C47778,Printer,5,666.80,3334.00,Delivered,Debit Card
8,ORD201031,2023-02-28 00:00:00,C59183,Phone,5,664.51,3322.55,Pending,Debit Card
9,ORD200463,2023-05-26 00:00:00,C25276,Laptop,5,662.78,3313.90,Shipped,Debit Card

In [26]:
query = """
SELECT
    CASE CAST(strftime('%w', Date) AS INTEGER)
        WHEN 0 THEN 'Sunday'
        WHEN 1 THEN 'Monday'
        WHEN 2 THEN 'Tuesday'
        WHEN 3 THEN 'Wednesday'
        WHEN 4 THEN 'Thursday'
        WHEN 5 THEN 'Friday'
        WHEN 6 THEN 'Saturday'
    END AS Day_of_Week,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY strftime('%w', Date)
ORDER BY CAST(strftime('%w', Date) AS INTEGER);
"""

result = pd.read_sql_query(query, conn)
display(result)

  Day_of_Week  Number_of_Orders  Total_Quantity  Total_Sales
0      Sunday               186             545    199194.84
1      Monday               174             522    184009.38
2     Tuesday               165             478    180780.14
3   Wednesday               163             482    160519.31
4    Thursday               166             505    182066.56
5      Friday               174             519    190598.20
6    Saturday               172             484    167593.53

In [27]:
query = """
SELECT
    PaymentMethod,
    OrderStatus,
    COUNT(*) AS Number_of_Orders,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY PaymentMethod, OrderStatus
ORDER BY PaymentMethod, Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   PaymentMethod OrderStatus  Number_of_Orders  Total_Sales
0           Cash     Pending                52     57258.11
1           Cash    Returned                57     56152.14
2           Cash   Cancelled                49     55900.71
3           Cash     Shipped                43     47617.64
4           Cash   Delivered                45     42857.69
5    Credit Card   Cancelled                54     64085.37
6    Credit Card     Pending                48     58543.12
7    Credit Card    Returned                49     53647.88
8    Credit Card   Delivered                43     46054.96
9    Credit Card     Shipped                40     41516.30
10    Debit Card     Pending                55     53626.54
11    Debit Card    Returned                51     49613.01
12    Debit Card   Delivered                43     45885.14
13    Debit Card     Shipped                39     45215.94
14    Debit Card   Cancelled                44     38020.55
15     Gift Card   Cancelled                50     62210.21
16     Gift Card     Shipped                56     55358.43
17     Gift Card    Returned                52     47874.54
18     Gift Card   Delivered                37     40682.88
19     Gift Card     Pending                35     40197.86
20        Online   Delivered                63     67119.65
21        Online     Shipped                57     56451.27
22        Online   Cancelled                53     56179.37
23        Online     Pending                47     46702.52
24        Online    Returned                38     35990.13

In [28]:
query = """
SELECT
    ReferralSource,
    Product,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY ReferralSource, Product
ORDER BY ReferralSource, Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   ReferralSource  Product  Number_of_Orders  Total_Quantity  Total_Sales
0           Email    Chair                41             121     47821.77
1           Email   Tablet                40             123     45373.45
2           Email  Printer                41             127     44853.05
3           Email    Phone                34              96     36528.67
4           Email   Laptop                33             104     35655.01
5           Email  Monitor                32             101     34861.90
6           Email     Desk                29              74     16714.70
7        Facebook  Monitor                37             112     40718.95
8        Facebook    Chair                37             120     40385.07
9        Facebook  Printer                36             101     39558.03
10       Facebook   Laptop                31              93     35701.38
11       Facebook     Desk                32             103     31994.63
12       Facebook   Tablet                31              81     31631.24
13       Facebook    Phone                24              64     30421.60
14         Google  Printer                41             120     42235.69
15         Google   Tablet                35             102     40221.21
16         Google    Phone                39             100     36083.79
17         Google     Desk                39             114     35643.09
18         Google    Chair                28              92     32744.63
19         Google   Laptop                33             103     31769.46
20         Google  Monitor                26              83     31743.61
21      Instagram   Laptop                40             131     48453.41
22      Instagram     Desk                41             125     47520.51
23      Instagram  Monitor                39             110     42385.10
24      Instagram    Chair                41             134     40959.45
25      Instagram   Tablet                41             104     35697.02
26      Instagram  Printer                31              92     34489.40
27      Instagram    Phone                26              74     25780.56
28       Referral   Laptop                36             104     40547.30
29       Referral     Desk                29              92     35587.00
30       Referral  Printer                32             102     34476.44
31       Referral    Chair                31              95     33709.19
32       Referral   Tablet                32              87     33646.03
33       Referral  Monitor                29              74     25941.85
34       Referral    Phone                33              77     22907.77

In [29]:
query = """
SELECT
    CASE
        WHEN CouponCode IS NULL THEN 'No Coupon'
        ELSE 'Coupon Used'
    END AS Coupon_Status,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
FROM orders
GROUP BY
    CASE
        WHEN CouponCode IS NULL THEN 'No Coupon'
        ELSE 'Coupon Used'
    END
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

,Coupon_Status,Number_of_Orders,Total_Quantity,Total_Sales,Average_Order_Value
0,Coupon Used,891,2594,942360.55,1057.64
1,No Coupon,309,941,322401.41,1043.37

In [30]:
query = """
SELECT
    CustomerID,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY CustomerID
HAVING COUNT(*) > 1
ORDER BY Number_of_Orders DESC, Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   CustomerID  Number_of_Orders  Total_Quantity  Total_Sales
0      C38840                 2               9      5723.23
1      C97593                 2               5      2855.22
2      C98474                 2               6      2175.34
3      C70659                 2               8      1853.96
4      C94569                 2               3      1675.35
5      C46651                 2               5      1360.89
6      C35852                 2               7      1248.39
7      C14847                 2               5      1097.81
8      C91155                 2               6       704.82
9      C21191                 2               3       647.77
10     C56969                 2               3       193.00

In [31]:
query = """
SELECT
    Quantity,
    COUNT(*) AS Number_of_Orders,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
FROM orders
GROUP BY Quantity
ORDER BY Quantity;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Quantity  Number_of_Orders  Total_Sales  Average_Order_Value
0         1               255     89728.29               351.88
1         2               240    165729.68               690.54
2         3               237    261276.18              1102.43
3         4               251    368090.96              1466.50
4         5               217    379936.85              1750.86

In [32]:
query = """
SELECT
    Product,
    OrderStatus,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY Product, OrderStatus
ORDER BY Product, Number_of_Orders DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

    Product OrderStatus  Number_of_Orders  Total_Quantity  Total_Sales
0     Chair   Cancelled                45             142     48660.98
1     Chair     Pending                41             145     48504.70
2     Chair   Delivered                33             105     31465.83
3     Chair     Shipped                31              99     40350.44
4     Chair    Returned                28              71     26638.16
5      Desk     Pending                38             124     41390.08
6      Desk   Cancelled                35             107     39587.69
7      Desk     Shipped                33              97     33424.89
8      Desk    Returned                32              86     28831.49
9      Desk   Delivered                32              94     24225.78
10   Laptop   Delivered                40             121     40714.43
11   Laptop    Returned                39             114     39654.30
12   Laptop   Cancelled                35             113     43761.72
13   Laptop     Pending                30              85     27758.88
14   Laptop     Shipped                29             102     40237.23
15  Monitor    Returned                36              97     40524.60
16  Monitor   Cancelled                35             102     37057.44
17  Monitor     Shipped                32              93     30924.82
18  Monitor   Delivered                31              96     35999.62
19  Monitor     Pending                29              92     31144.93
20    Phone   Delivered                38             101     40345.41
21    Phone    Returned                31              77     29164.20
22    Phone   Cancelled                31              80     28023.26
23    Phone     Shipped                28              63     21996.64
24    Phone     Pending                28              90     32192.88
25  Printer     Shipped                42             124     44397.41
26  Printer    Returned                38             114     35939.09
27  Printer     Pending                37             104     38546.22
28  Printer   Cancelled                35             112     38675.16
29  Printer   Delivered                29              88     38054.73
30   Tablet    Returned                43             123     42525.86
31   Tablet     Shipped                40             102     34828.15
32   Tablet     Pending                34              84     36790.46
33   Tablet   Cancelled                34             103     40629.96
34   Tablet   Delivered                28              85     31794.52

In [33]:
query = """
SELECT
    strftime('%Y', Date) AS Year,
    Product,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY strftime('%Y', Date), Product
ORDER BY Year, Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

    Year  Product  Number_of_Orders  Total_Quantity  Total_Sales
0   2023  Printer                82             243     95513.73
1   2023    Chair                80             244     87585.58
2   2023   Tablet                77             225     86678.92
3   2023   Laptop                74             229     83231.66
4   2023  Monitor                71             205     75876.42
5   2023    Phone                60             178     62766.40
6   2023     Desk                66             200     60990.53
7   2024    Chair                70             237     84785.75
8   2024   Laptop                63             206     75611.41
9   2024  Monitor                63             177     68450.23
10  2024  Printer                65             201     64853.85
11  2024    Phone                65             160     64143.70
12  2024   Tablet                67             176     63213.11
13  2024     Desk                66             194     59177.82
14  2025     Desk                38             114     47291.58
15  2025   Tablet                35              96     36676.92
16  2025  Printer                34              98     35245.03
17  2025   Laptop                36             100     33283.49
18  2025  Monitor                29              98     31324.76
19  2025    Phone                31              73     24812.29
20  2025    Chair                28              81     23248.78

In [34]:
query = """
SELECT
    strftime('%Y-%m', Date) AS Month,
    COUNT(*) AS Number_of_Orders,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
FROM orders
GROUP BY strftime('%Y-%m', Date)
ORDER BY Month;
"""

result = pd.read_sql_query(query, conn)
display(result)

      Month  Number_of_Orders  Total_Sales  Average_Order_Value
0   2023-01                47     56685.75              1206.08
1   2023-02                37     40117.66              1084.26
2   2023-03                43     48609.37              1130.45
3   2023-04                31     27751.71               895.22
4   2023-05                49     63836.84              1302.79
5   2023-06                45     49500.19              1100.00
6   2023-07                44     42820.66               973.20
7   2023-08                51     54352.14              1065.73
8   2023-09                29     29526.67              1018.16
9   2023-10                47     52607.85              1119.32
10  2023-11                41     43079.67              1050.72
11  2023-12                46     43754.73               951.19
12  2024-01                32     38528.08              1204.00
13  2024-02                32     36909.57              1153.42
14  2024-03                36     36030.90              1000.86
15  2024-04                50     49613.14               992.26
16  2024-05                34     27909.11               820.86
17  2024-06                53     68068.54              1284.31
18  2024-07                43     42963.98               999.16
19  2024-08                28     31991.07              1142.54
20  2024-09                44     39794.98               904.43
21  2024-10                31     37226.97              1200.87
22  2024-11                35     32413.76               926.11
23  2024-12                41     38785.77               945.99
24  2025-01                27     29099.40              1077.76
25  2025-02                37     35317.55               954.53
26  2025-03                49     39200.66               800.01
27  2025-04                32     31821.20               994.41
28  2025-05                37     43396.64              1172.88
29  2025-06                49     53047.40              1082.60

In [35]:
query = """
SELECT
    OrderStatus,
    COUNT(DISTINCT CustomerID) AS Unique_Customers,
    COUNT(*) AS Number_of_Orders,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY OrderStatus
ORDER BY Unique_Customers DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

  OrderStatus  Unique_Customers  Number_of_Orders  Total_Sales
0   Cancelled               250               250    276396.21
1    Returned               247               247    243277.70
2     Shipped               235               235    246159.58
3     Pending               235               237    256328.15
4   Delivered               231               231    242600.32

In [36]:
query = """
SELECT
    CustomerID,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY CustomerID
ORDER BY Number_of_Orders DESC, Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

  CustomerID  Number_of_Orders  Total_Quantity  Total_Sales
0     C38840                 2               9      5723.23
1     C97593                 2               5      2855.22
2     C98474                 2               6      2175.34
3     C70659                 2               8      1853.96
4     C94569                 2               3      1675.35
5     C46651                 2               5      1360.89
6     C35852                 2               7      1248.39
7     C14847                 2               5      1097.81
8     C91155                 2               6       704.82
9     C21191                 2               3       647.77

In [37]:
query = """
SELECT
    Product,
    PaymentMethod,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY Product, PaymentMethod
ORDER BY Product, Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

    Product PaymentMethod  Number_of_Orders  Total_Quantity  Total_Sales
0     Chair        Online                47             155     54341.91
1     Chair     Gift Card                36             106     38064.35
2     Chair          Cash                34             104     35902.59
3     Chair   Credit Card                30             101     35405.05
4     Chair    Debit Card                31              96     31906.21
5      Desk     Gift Card                39             114     39498.39
6      Desk   Credit Card                37             110     37473.98
7      Desk          Cash                33             104     31644.97
8      Desk        Online                27              84     29526.11
9      Desk    Debit Card                34              96     29316.48
10   Laptop          Cash                45             146     48676.40
11   Laptop     Gift Card                33             104     42057.39
12   Laptop    Debit Card                36             102     35713.68
13   Laptop   Credit Card                28              91     35308.12
14   Laptop        Online                31              92     30370.97
15  Monitor   Credit Card                34             114     42473.64
16  Monitor        Online                34              86     35239.46
17  Monitor     Gift Card                29              83     33301.19
18  Monitor          Cash                34             102     32847.01
19  Monitor    Debit Card                32              95     31790.11
20    Phone   Credit Card                35              90     32317.43
21    Phone    Debit Card                30              80     31731.75
22    Phone     Gift Card                34              97     31525.70
23    Phone        Online                33              73     30150.22
24    Phone          Cash                24              71     25997.29
25  Printer          Cash                41             122     46940.27
26  Printer   Credit Card                39             120     43289.52
27  Printer        Online                39             115     39538.50
28  Printer    Debit Card                33              96     33165.09
29  Printer     Gift Card                29              89     32679.23
30   Tablet        Online                47             126     43275.77
31   Tablet    Debit Card                36              99     38737.86
32   Tablet          Cash                35             104     37777.76
33   Tablet   Credit Card                31              86     37579.89
34   Tablet     Gift Card                30              82     29197.67

In [38]:
query = """
SELECT
    ReferralSource,
    OrderStatus,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY ReferralSource, OrderStatus
ORDER BY ReferralSource, Number_of_Orders DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   ReferralSource OrderStatus  Number_of_Orders  Total_Quantity  Total_Sales
0           Email   Delivered                60             183     64553.52
1           Email   Cancelled                59             182     60266.49
2           Email    Returned                49             141     53755.05
3           Email     Pending                46             137     47639.34
4           Email     Shipped                36             103     35594.15
5        Facebook    Returned                56             161     64358.38
6        Facebook     Shipped                49             125     41040.22
7        Facebook   Delivered                42             137     52149.38
8        Facebook   Cancelled                42             135     50935.74
9        Facebook     Pending                39             116     41927.18
10         Google   Cancelled                58             169     57582.70
11         Google     Shipped                49             150     54160.98
12         Google     Pending                47             153     59518.19
13         Google   Delivered                44             127     41406.25
14         Google    Returned                43             115     37773.36
15      Instagram     Pending                69             208     67258.72
16      Instagram    Returned                55             149     49113.88
17      Instagram   Delivered                52             149     51299.56
18      Instagram     Shipped                42             135     56947.22
19      Instagram   Cancelled                41             129     50666.07
20       Referral     Shipped                59             167     58417.01
21       Referral   Cancelled                50             144     56945.21
22       Referral    Returned                44             116     38277.03
23       Referral     Pending                36             110     39984.72
24       Referral   Delivered                33              94     33191.61

In [39]:
query = """
SELECT
    Product,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(AVG(Quantity), 2) AS Average_Quantity_Per_Order,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY Product
ORDER BY Average_Quantity_Per_Order DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

,Product,Number_of_Orders,Total_Quantity,Average_Quantity_Per_Order,Total_Sales
0,Chair,178,562,3.16,195620.11
1,Laptop,173,535,3.09,192126.56
2,Printer,181,542,2.99,195612.61
3,Desk,170,508,2.99,167459.93
4,Monitor,163,480,2.94,175651.41
5,Tablet,179,497,2.78,186568.95
6,Phone,156,411,2.63,151722.39

In [40]:
query = """
SELECT
    DATE(Date) AS Order_Date,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY DATE(Date)
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Order_Date  Number_of_Orders  Total_Quantity  Total_Sales
0  2023-08-20                 8              32      9290.49
1  2023-02-16                 5              21      8448.00
2  2024-04-07                 7              19      8085.26
3  2023-11-24                 3              12      7842.55
4  2024-06-19                 4              14      7129.53
5  2025-03-15                 6              16      6765.40
6  2023-02-28                 2              10      6692.75
7  2023-03-27                 4              14      6575.55
8  2023-06-11                 4              14      6527.58
9  2025-06-24                 5              16      6358.22

In [41]:
query = """
SELECT
    PaymentMethod,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
FROM orders
GROUP BY PaymentMethod
ORDER BY Average_Order_Value DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

,PaymentMethod,Number_of_Orders,Total_Quantity,Total_Sales,Average_Order_Value
0,Credit Card,234,712,263847.63,1127.55
1,Gift Card,230,675,246323.92,1070.97
2,Cash,246,753,259786.29,1056.04
3,Online,258,731,262442.94,1017.22
4,Debit Card,232,664,232361.18,1001.56

In [42]:
query = """
SELECT
    COALESCE(CouponCode, 'No Coupon') AS Coupon_Code,
    OrderStatus,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY CouponCode, OrderStatus
ORDER BY Coupon_Code, Number_of_Orders DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Coupon_Code OrderStatus  Number_of_Orders  Total_Quantity  Total_Sales
0     FREESHIP   Cancelled                67             212     76366.09
1     FREESHIP     Pending                63             178     68984.90
2     FREESHIP     Shipped                61             177     61588.64
3     FREESHIP    Returned                61             169     62563.01
4     FREESHIP   Delivered                61             178     65534.35
5    No Coupon    Returned                76             212     75991.31
6    No Coupon     Shipped                64             180     65373.85
7    No Coupon     Pending                59             198     66496.36
8    No Coupon   Cancelled                58             188     61065.81
9    No Coupon   Delivered                52             163     53474.08
10      SAVE10   Delivered                63             197     69554.36
11      SAVE10     Pending                62             197     71221.25
12      SAVE10   Cancelled                58             152     58946.94
13      SAVE10     Shipped                56             172     62231.95
14      SAVE10    Returned                47             126     42885.52
15    WINTER15   Cancelled                67             207     80017.37
16    WINTER15    Returned                63             175     61837.86
17    WINTER15   Delivered                55             152     54037.53
18    WINTER15     Shipped                54             151     56965.14
19    WINTER15     Pending                53             151     49625.64

In [43]:
query = """
SELECT
    ReferralSource,
    PaymentMethod,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY ReferralSource, PaymentMethod
ORDER BY ReferralSource, Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   ReferralSource PaymentMethod  Number_of_Orders  Total_Quantity  Total_Sales
0           Email    Debit Card                59             176     63656.03
1           Email   Credit Card                53             161     56405.96
2           Email          Cash                48             147     51494.53
3           Email        Online                49             138     50405.51
4           Email     Gift Card                41             124     39846.52
5        Facebook        Online                52             149     58608.93
6        Facebook   Credit Card                44             144     56228.91
7        Facebook          Cash                52             156     49888.50
8        Facebook     Gift Card                41             116     47186.28
9        Facebook    Debit Card                39             109     38498.28
10         Google   Credit Card                46             142     56014.45
11         Google     Gift Card                46             144     53697.60
12         Google        Online                55             153     49272.62
13         Google          Cash                46             137     46274.03
14         Google    Debit Card                48             138     45182.78
15      Instagram        Online                60             179     62541.05
16      Instagram          Cash                56             185     60491.51
17      Instagram     Gift Card                54             155     58474.24
18      Instagram    Debit Card                45             132     48187.39
19      Instagram   Credit Card                44             119     45591.26
20       Referral          Cash                44             128     51637.72
21       Referral   Credit Card                47             146     49607.05
22       Referral     Gift Card                48             136     47119.28
23       Referral        Online                42             112     41614.83
24       Referral    Debit Card                41             109     36836.70

In [44]:
query = """
SELECT
    Product,
    COALESCE(CouponCode, 'No Coupon') AS Coupon_Code,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY Product, CouponCode
ORDER BY Product, Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

    Product Coupon_Code  Number_of_Orders  Total_Quantity  Total_Sales
0     Chair   No Coupon                48             163     58645.93
1     Chair    FREESHIP                44             128     52717.74
2     Chair      SAVE10                41             130     47948.88
3     Chair    WINTER15                45             141     36307.56
4      Desk   No Coupon                41             142     48222.17
5      Desk    FREESHIP                45             126     44480.34
6      Desk    WINTER15                49             137     42775.02
7      Desk      SAVE10                35             103     31982.40
8    Laptop    FREESHIP                45             140     53433.53
9    Laptop   No Coupon                46             149     51256.92
10   Laptop    WINTER15                40             128     45133.82
11   Laptop      SAVE10                42             118     42302.29
12  Monitor    WINTER15                44             122     54268.26
13  Monitor   No Coupon                47             148     45010.92
14  Monitor      SAVE10                35             104     40820.56
15  Monitor    FREESHIP                37             106     35551.67
16    Phone    FREESHIP                44             123     50170.16
17    Phone      SAVE10                46             124     42606.14
18    Phone   No Coupon                39              90     33239.13
19    Phone    WINTER15                27              74     25706.96
20  Printer    FREESHIP                50             158     55758.43
21  Printer      SAVE10                50             152     54540.12
22  Printer    WINTER15                39             105     43793.76
23  Printer   No Coupon                42             127     41520.30
24   Tablet    WINTER15                48             129     54498.16
25   Tablet      SAVE10                37             113     44639.63
26   Tablet   No Coupon                46             122     44506.04
27   Tablet    FREESHIP                48             133     42925.12

In [45]:
query = """
SELECT
    strftime('%Y-%m', Date) AS Month,
    Product,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales
FROM orders
GROUP BY strftime('%Y-%m', Date), Product
ORDER BY Month, Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

       Month  Product  Number_of_Orders  Total_Quantity  Total_Sales
0    2023-01    Chair                 9              26     13555.72
1    2023-01  Monitor                 9              28     12397.56
2    2023-01   Laptop                 7              21      8987.38
3    2023-01    Phone                 6              24      8347.76
4    2023-01  Printer                 8              24      7091.55
..       ...      ...               ...             ...          ...
204  2025-06   Laptop                 8              23      8332.67
205  2025-06    Chair                 7              26      7254.19
206  2025-06     Desk                 7              19      7219.74
207  2025-06  Monitor                 5              16      5646.25
208  2025-06  Printer                 5              15      3935.24

[209 rows x 5 columns]

In [46]:
query = """
SELECT
    Product,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(AVG(UnitPrice), 2) AS Average_Unit_Price,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
FROM orders
GROUP BY Product
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

,Product,Number_of_Orders,Total_Quantity,Total_Sales,Average_Unit_Price,Average_Order_Value
0,Chair,178,562,195620.11,355.66,1098.99
1,Printer,181,542,195612.61,351.71,1080.73
2,Laptop,173,535,192126.56,357.71,1110.56
3,Tablet,179,497,186568.95,367.68,1042.28
4,Monitor,163,480,175651.41,358.66,1077.62
5,Desk,170,508,167459.93,329.61,985.06
6,Phone,156,411,151722.39,375.22,972.58

In [47]:
query = """
SELECT
    OrderID,
    Date,
    Product,
    Quantity,
    TotalPrice,
    OrderStatus
FROM orders
WHERE Date >= '2024-01-01'
  AND TotalPrice >= 2000
ORDER BY TotalPrice DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

       OrderID                 Date  Product  Quantity  TotalPrice OrderStatus
0    ORD200326  2024-07-01 00:00:00   Laptop         5     3352.40    Returned
1    ORD200361  2024-06-29 00:00:00  Printer         5     3299.25   Delivered
2    ORD200367  2024-04-25 00:00:00   Laptop         5     3293.85     Pending
3    ORD200837  2025-06-14 00:00:00    Chair         5     3277.75   Delivered
4    ORD200527  2024-08-19 00:00:00    Chair         5     3267.35   Cancelled
..         ...                  ...      ...       ...         ...         ...
96   ORD200304  2024-10-18 00:00:00  Monitor         5     2043.65   Delivered
97   ORD200458  2024-07-02 00:00:00  Monitor         4     2042.32    Returned
98   ORD200807  2024-11-10 00:00:00  Monitor         3     2028.63   Delivered
99   ORD200181  2024-08-31 00:00:00  Printer         5     2021.95     Shipped
100  ORD200915  2024-02-16 00:00:00   Laptop         4     2011.96     Shipped

[101 rows x 6 columns]

In [48]:
query = """
SELECT
    Product,
    COUNT(*) AS Number_of_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
FROM orders
GROUP BY Product
HAVING COUNT(*) > 170
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Product  Number_of_Orders  Total_Quantity  Total_Sales  Average_Order_Value
0    Chair               178             562    195620.11              1098.99
1  Printer               181             542    195612.61              1080.73
2   Laptop               173             535    192126.56              1110.56
3   Tablet               179             497    186568.95              1042.28

In [49]:
query = """
SELECT
    Product,
    ROUND(SUM(TotalPrice), 2) AS Total_Sales,
    ROUND(
        SUM(TotalPrice) * 100.0 / (SELECT SUM(TotalPrice) FROM orders),
        2
    ) AS Sales_Percentage
FROM orders
GROUP BY Product
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Product  Total_Sales  Sales_Percentage
0    Chair    195620.11             15.47
1  Printer    195612.61             15.47
2   Laptop    192126.56             15.19
3   Tablet    186568.95             14.75
4  Monitor    175651.41             13.89
5     Desk    167459.93             13.24
6    Phone    151722.39             12.00